"""add last_error columns to project_postgres_connections

Revision ID: 062d52f983f9
Revises: 395e7734f751
Create Date: 2025-06-22 23:54:31.138577

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "062d52f983f9"
down_revision: Union[str, None] = "395e7734f751"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_postgres_connections",
        sa.Column("last_error_text", sa.Text(), nullable=True),
    )
    op.add_column(
        "project_postgres_connections",
        sa.Column("last_error_timestamp", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_postgres_connections", "last_error_timestamp")
    op.drop_column("project_postgres_connections", "last_error_text")
    # ### end Alembic commands ###
