"""Add fork_reason column to user_mundiai_maps

Revision ID: 5ad3e7c82829
Revises: 74cb3a38fe0f
Create Date: 2025-07-10 22:00:17.081726

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5ad3e7c82829"
down_revision: Union[str, None] = "74cb3a38fe0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_mundiai_maps", sa.Column("fork_reason", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_mundiai_maps", "fork_reason")
    # ### end Alembic commands ###
