"""Add parent_map_id column to user_mundiai_maps

Revision ID: 74cb3a38fe0f
Revises: 07c7ae795a24
Create Date: 2025-07-11 20:03:39.611614

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "74cb3a38fe0f"
down_revision: Union[str, None] = "07c7ae795a24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_mundiai_maps",
        sa.Column("parent_map_id", sa.String(length=12), nullable=True),
    )
    op.create_foreign_key(
        None, "user_mundiai_maps", "user_mundiai_maps", ["parent_map_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_mundiai_maps", type_="foreignkey")
    op.drop_column("user_mundiai_maps", "parent_map_id")
    # ### end Alembic commands ###
