"""add postgis_attribute_column_list to map_layers

Revision ID: 920b5ccbca48
Revises: 07c7ae795a24
Create Date: 2025-07-25 21:33:28.439022

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "920b5ccbca48"
down_revision: Union[str, None] = "07c7ae795a24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "map_layers",
        sa.Column(
            "postgis_attribute_column_list", sa.ARRAY(sa.String()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("map_layers", "postgis_attribute_column_list")
    # ### end Alembic commands ###
