"""add_soft_delete_timestamp_to_postgres_connections

Revision ID: 978c47f3de28
Revises: 062d52f983f9
Create Date: 2025-06-23 18:38:29.370674

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "978c47f3de28"
down_revision: Union[str, None] = "062d52f983f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_postgres_connections",
        sa.Column("soft_deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_postgres_connections", "soft_deleted_at")
    # ### end Alembic commands ###
