"""Update models

Revision ID: ca935a17526b
Revises: d3d460876d22
Create Date: 2025-07-16 19:32:26.907530

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ca935a17526b"
down_revision: Union[str, None] = "d3d460876d22"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_completion_messages",
        sa.Column("conversation_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        None, "chat_completion_messages", "conversations", ["conversation_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "chat_completion_messages", type_="foreignkey")
    op.drop_column("chat_completion_messages", "conversation_id")
    # ### end Alembic commands ###
