"""add_conversations_table

Revision ID: d3d460876d22
Revises: 5ad3e7c82829
Create Date: 2025-07-16 04:34:04.686116

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d3d460876d22"
down_revision: Union[str, None] = "5ad3e7c82829"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.String(length=12), nullable=False),
        sa.Column("owner_uuid", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("soft_deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["user_mundiai_projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("messages", sa.Column("conversation_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "messages", "conversations", ["conversation_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.drop_column("messages", "conversation_id")
    op.drop_table("conversations")
    # ### end Alembic commands ###
