"""add table_count to project_postgres_summary

Revision ID: fad2e5b46554
Revises: 978c47f3de28
Create Date: 2025-06-26 00:46:51.287919

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "fad2e5b46554"
down_revision: Union[str, None] = "978c47f3de28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_postgres_summary",
        sa.Column("table_count", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_postgres_summary", "table_count")
    # ### end Alembic commands ###
